### ISSUE TITLE
[Dependency]: Stub implementation for CHIRP workflow

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-workflows#8]
Who: SE to U-SPS:
What: Provide a complete end-to-end CWL workflow for CHIRP possibly using stub implementations for all 5 steps.
When: April 2023

**Comment by LucaCinquini** [comment]
2023-04-22
The stub implementation of the E2E workflow fails:
cwltool chirp-rebinning-e2e-workflow.cwl chirp-rebinning-e2e-workflow_input_sample_job_1.yml

The first step (CMR search) will succeed if the input parameter is changed to the this collection name:
input_cmr_collection_name: "C2011289787-GES_DISC"

But then the workflow will fail at the rebinning step:

INFO [workflow chirp-rebinning] start
INFO [workflow chirp-rebinning] starting step stage_in_input_filename
INFO [step stage_in_input_filename] start
INFO [job stage_in_input_filename] /private/tmp/docker_tmpfjp22las$ docker \
    run \
    -i \
    --mount=type=bind,source=/private/tmp/docker_tmpfjp22las,target=/jNWCIv \
    --mount=type=bind,source=/private/tmp/docker_tmpsrobzej4,target=/tmp \
    --mount=type=bind,source=/private/tmp/docker_tmpt4cl5b0m/inputs.json,target=/tmp/inputs.json,readonly \
    --workdir=/jNWCIv \
    --read-only=true \
    --log-driver=none \
    --user=502:20 \
    --rm \
    --cidfile=/private/tmp/docker_tmpxrmnib8u/20230422050257-434743.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/jNWCIv \
    jplzhan/ci-generated-images:jplzhan.maap-ci-stage-io.v9 \
    /bin/sh \
    -c \
    python3 /home/jovyan/stage_in.py /tmp/inputs.json S3_unsigned > /private/tmp/docker_tmpfjp22las/76522e5e096856c6d1dad0cf4de27b5a6919e6c6
Traceback (most recent call last):
  File "/usr/local/bin/repo2docker-entrypoint", line 110, in <module>
    main()
  File "/usr/local/bin/repo2docker-entrypoint", line 38, in main
    log_file = open(log_path, "ab")
OSError: [Errno 30] Read-only file system: '/home/jovyan/.jupyter-server-log.txt'
INFO [job stage_in_input_filename] Max memory used: 0MiB
WARNING [job stage_in_input_filename] completed permanentFail
WARNING [step stage_in_input_filename] completed permanentFail
INFO [workflow chirp-rebinning] completed permanentFail
WARNING [step chirp-rebinning] completed permanentFail
INFO [workflow ] completed permanentFail

**Comment by LucaCinquini** [comment]
Mike provided a working stub implementation on 4/25/2023. From the Slack channel:

cwltool --no-read-only chirp-rebinning-e2e-workflow.cwl chirp-rebinning-e2e-workflow_input_sample_job_1.yml

INFO /Users/gangl/miniconda3/bin/cwltool 3.1.20230213100550
INFO Resolved 'chirp-rebinning-e2e-workflow.cwl' to 'file:///Users/gangl/dev/unity/sounder-sips-chirp-workflows/chirp-rebinning-e2e-workflow.cwl'
INFO [workflow ] start
INFO [workflow ] starting step cmr-step
INFO [step cmr-step] start
INFO [workflow cmr-step] start
INFO [workflow cmr-step] starting step cmr-search
INFO [step cmr-search] start
INFO [job cmr-search] /private/tmp/docker_tmpsv9m_vbs$ docker \
    run \
    -i \
    --mount=type=bind,source=/private/tmp/docker_tmpsv9m_vbs,target=/ftbHas \
    --mount=type=bind,source=/private/tmp/docker_tmpg42ciy0c,target=/tmp \
    --workdir=/ftbHas \
    --log-driver=none \
    --user=903283592:703763885 \
    --rm \
    --cidfile=/private/tmp/docker_tmpfap5i6o0/20230425170513-505250.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/ftbHas \
    --env=CMR_BASE_URL=https://cmr.earthdata.nasa.gov/ \
    --env=COLLECTION_ID=C2011289787-GES_DISC \
    --env=DATE_FROM=2016-08-22T00:10:00Z \
    --env=DATE_TO=2016-09-06T23:59:59Z \
    --env=FILTER_ONLY_ASSETS=TRUE \
    --env=GRANULES_SEARCH_DOMAIN=CMR \
    --env=LIMITS=-1 \
    ghcr.io/unity-sds/unity-data-services:3.3.1 \
    SEARCH > /private/tmp/docker_tmpsv9m_vbs/cmr-results.json
2023-04-26 00:05:14,240 [INFO] [root::13] starting SEARCH script
2023-04-26 00:05:14,508 [DEBUG] [urllib3.connectionpool::1003] Starting new HTTPS connection (1): cmr.earthdata.nasa.gov:443
2023-04-26 00:05:15,373 [DEBUG] [urllib3.connectionpool::456] [https://cmr.earthdata.nasa.gov:443](https://cmr.earthdata.nasa.gov/) "POST /search/granules.stac HTTP/1.1" 200 None
2023-04-26 00:05:15,822 [DEBUG] [urllib3.connectionpool::1003] Starting new HTTPS connection (1): cmr.earthdata.nasa.gov:443
2023-04-26 00:05:16,616 [DEBUG] [urllib3.connectionpool::456] [https://cmr.earthdata.nasa.gov:443](https://cmr.earthdata.nasa.gov/) "POST /search/granules.stac HTTP/1.1" 200 None
INFO [job cmr-search] Max memory used: 1461MiB
INFO [job cmr-search] completed success
INFO [step cmr-search] completed success
INFO [workflow cmr-step] completed success
INFO [step cmr-step] completed success
INFO [workflow ] starting step chirp-rebinning
INFO [step chirp-rebinning] start
INFO [workflow chirp-rebinning] start
INFO [workflow chirp-rebinning] starting step process
INFO [step process] start
INFO [job process] /private/tmp/docker_tmpb2dptg36$ python \
    process.py > /private/tmp/docker_tmpb2dptg36/process-results.json
INFO [job process] Max memory used: 6MiB
INFO [job process] completed success
INFO [step process] completed success
INFO [workflow chirp-rebinning] completed success
INFO [step chirp-rebinning] completed success
INFO [workflow ] starting step data-catalog
INFO [step data-catalog] start
INFO [workflow data-catalog] start
INFO [workflow data-catalog] starting step catalog
INFO [step catalog] start
INFO [job catalog] /private/tmp/docker_tmpba8o6vur$ python \
    catalog.py > /private/tmp/docker_tmpba8o6vur/uds-results.json
INFO [job catalog] completed success
INFO [step catalog] completed success
INFO [workflow data-catalog] completed success
INFO [step data-catalog] completed success
INFO [workflow ] completed success
{}INFO Final process status is success
[6:07](https://jpl.slack.com/archives/G01EJJV7UH4/p1682467629085539)
the inputs/outputs of the commands are all STAC
[6:07](https://jpl.slack.com/archives/G01EJJV7UH4/p1682467675983239)

so cmr returns stac, which is converted to stage-in, then processed, then the output of stage-out should be STAC as well (here are the locations of data and metadata within the data storage), which would then get converted into catalog entries
[6:08](https://jpl.slack.com/archives/G01EJJV7UH4/p1682467686588889)
point is, you cna deploy that and run it if you’d like

Tested and verified by Luca on 4/26/2023
